### ISSUE TITLE
setName method causes inconsitence

### ISSUE THREAD

**Issue by ThemePoint** [marcoschwepp/CookieManager#3]
The `setName` method should not be there. Cookie is based on name what should not be changed.
https://github.com/marcoschwepp/CookieManager/blob/c46fb55fc9d39d9cae4e9d7555e669d9e6f8d6b2/src/Cookie.php#L75

Possible inconsitence:
If you rename a cookie it will create a new cookie with the new name but do not delete the old on.
If you want to create a cookie with a new name create it instead of rename it.

**Comment by marcoschwepp** [comment]
that is absolutly correct, thanks :) i will remove it.
